name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v1
            - uses: ArtiomTr/jest-coverage-report-action@v1.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  test-script: npx jest src/**/*.test.ts --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary" --outputFile="report.json"
